**Варіант №1**

Завдання 1.
1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та
виведіть його значення.


In [1]:
import numpy as np

vector = np.arange(1, 11)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


Завдання 2.
1. Створіть двовимірний масив (матрицю) розміром 4x4, заповніть його одиницями та
виведіть його значення.


In [2]:
import numpy as np

matrix = np.ones((3, 3), dtype=int)
print(matrix)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


Завдання 3
1. Створіть масив розміром 4x4, заповніть його випадковими цілими числами в діапазоні
від 1 до 5 та виведіть його значення.

In [3]:
import numpy as np

matrix = np.random.randint(6, size=(4,4))
print(matrix)

[[1 5 3 0]
 [1 3 3 0]
 [2 0 4 4]
 [2 0 3 0]]


Завдання 4
1. Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в
діапазоні від 0 до 1 та виведіть його значення.

In [4]:
import numpy as np

matrix = np.random.rand(3, 3)
print(matrix)

[[0.5583393  0.83022172 0.5111889 ]
 [0.20141645 0.69936123 0.22908356]
 [0.90051735 0.21747573 0.51298729]]


Завдання 5
1. Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими
числами в діапазоні від 1 до 20 та виконайте на них поелементні операції додавання,
віднімання та множення.

In [5]:
import numpy as np

a = np.random.randint(1, 21, size=6)
b = np.random.randint(1, 21, size=6)

add = a + b
s = a - b
m = a * b

print("Перший масив:", a)
print("Другий масив:", b)
print("Додавання:", add)
print("Віднімання:", s)
print("Множення:", m)

Перший масив: [ 6  1 17 20  2  6]
Другий масив: [ 2  3  8 16  7  1]
Додавання: [ 8  4 25 36  9  7]
Віднімання: [ 4 -2  9  4 -5  5]
Множення: [ 12   3 136 320  14   6]


Завдання 6
1. Створіть два матриці 2x2, заповніть їх довільними цілими числами та знайдіть їх
добуток.


In [8]:
import numpy as np

a = np.matrix([[1, 2], [4, 5]])
b = np.matrix([[7, 8],[2, 3]])

c = np.dot(a, b)
print("Добуток матриць:")
print(c)

Добуток матриць:
[[11 14]
 [38 47]]


Завдання 7
1. Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами
в діапазоні від 1 до 10 та перемножте їх між собою.


In [9]:
import numpy as np

a = np.matrix(np.random.randint(1, 11, size=(3, 2)))
print("Матриця А:")
print(a)

b = np.matrix(np.random.randint(1, 11, size=(2, 4)))
print("\nМатриця В:")
print(b)

c = np.dot(a, b)
print("\nДобуток матриць A і B:")
print(c)

Перша матриця:
[[10  7]
 [ 6  9]
 [ 9  3]]

Друга матриця:
[[ 8  7  9 10]
 [ 6  7  6  7]]

Добуток матриць A і B:
[[122 119 132 149]
 [102 105 108 123]
 [ 90  84  99 111]]


Завдання 8
1. Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні
від 1 до 7 та знайдіть її обернену матрицю.

In [13]:
import numpy as np

a = np.matrix(np.random.randint(1, 8, size=(2, 2)))
print("Матриця:")
a_inv = np.linalg.inv(a)
print(a)
print("Обернена матриця:")
print(a_inv)

Матриця:
[[3 1]
 [6 6]]
Обернена матриця:
[[ 0.5        -0.08333333]
 [-0.5         0.25      ]]


Завдання 9.
1. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
діапазоні від 0 до 1 та транспонуйте її.


In [14]:
import numpy as np

a = np.array([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6], [0.7, 0.8, 0.9]])
print("Матриця a:")
print(a)
a_t = a.transpose()
print("Транспонована матриця:")
print(a_t)

Матриця a:
[[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]]
Транспонована матриця:
[[0.1 0.4 0.7]
 [0.2 0.5 0.8]
 [0.3 0.6 0.9]]


Завдання 10
1. Створіть матрицю розміром 3x4 та вектор розміром 4 x1, заповніть їх випадковими
цілими числами в діапазоні від 1 до 10 та знайдіть добуток матриці на вектор.


In [15]:
import numpy as np

a = np.random.randint(1, 11, size=(3, 4))
print("Матриця:")
print(a)

v = np.random.randint(1, 11, size=(4, 1))
print("\nВектор:")
print(v)

c = np.dot(a, v)
print("\nДобуток матриці на вектор:")
print(c)


Матриця:
[[10  3  1  9]
 [ 2  3  4 10]
 [ 1  6  3  4]]

Вектор:
[[6]
 [7]
 [8]
 [1]]

Добуток матриці на вектор:
[[98]
 [75]
 [76]]


Завдання 11
1. Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю
випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими цілими
числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

In [ ]:
import numpy as np

a = np.random.randint(1, 11, size=(2, 3))
print("Матриця:")
print(a)

v = np.random.randint(1, 11, size=(3, 1))
print("\nВектор:")
print(v)

c = np.dot(a, v)
print("\nДобуток матриці на вектор:")
print(c)


Завдання 12
1. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в
діапазоні від 1 до 10 та знайдіть їхню суму.

In [ ]:
import numpy as np

a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))

print("Матриця 1:")
print(a)

print("\nМатриця 2:")
print(b)

c = a + b
print("\nСума матриць:")
print(c)


Завдання 13
1. Створіть дві матриці розміром 2x2, заповніть їх випадковими дійсними числами в
діапазоні від 0 до 1 та знайдіть їх добуток.

In [16]:
import numpy as np

a = np.random.rand(2, 2)
b = np.random.rand(2, 2)

print("Матриця 1:")
print(a)

print("\nМатриця 2:")
print(b)

c = np.dot(a, b)
print("\nДобуток матриць:")
print(c)


Матриця 1:
[[0.89879375 0.35432363]
 [0.49206633 0.61188404]]

Матриця 2:
[[0.29868058 0.80050328]
 [0.93815913 0.34758086]]

Добуток матриць:
[[0.60086419 0.84264345]
 [0.72101526 0.60657989]]


Завдання 14
1. Створіть матрицю розміром 5x5, заповніть її випадковими дійсними числами в
діапазоні від 0 до 1 та знайдіть суму елементів матриці.


In [17]:
import numpy as np

a = np.random.rand(5, 5)
print("Матриця:")
print(a)

b = np.sum(a)
print("\nСума елементів матриці:")
print(b)


Матриця:
[[0.62869949 0.66346603 0.83450666 0.845187   0.40112175]
 [0.45939893 0.06723311 0.64833778 0.79642173 0.96303797]
 [0.21917028 0.50838672 0.82641939 0.83638463 0.79549126]
 [0.12196575 0.47799374 0.20047183 0.68308928 0.32288218]
 [0.94109102 0.4202578  0.40205977 0.17047895 0.96067918]]

Сума елементів матриці:
14.194232243172522


Завдання 15
1. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного
рядка матриці.

In [18]:
import numpy as np

a = 2 * np.random.rand(3, 3) - 1
print("Матриця:")
print(a)

row_sums = np.sum(a, axis=1).reshape(-1, 1)
print("\nВектор-стовпчик з сумою елементів кожного рядка:")
print(row_sums)


Матриця:
[[ 0.34134096 -0.80570747  0.83358182]
 [ 0.91883515 -0.01144293 -0.27159394]
 [-0.69519827  0.50012398 -0.45986279]]

Вектор-стовпчик з сумою елементів кожного рядка:
[[ 0.36921531]
 [ 0.63579828]
 [-0.65493709]]
